Repository atlp-rwanda/e-comm-team-emma25-bn, pull requests merged in 2023-02, with the labels that each got.

#15 fix: logout
  package-lock.json
  package.json
  src/controllers/authController.ts
  src/redis_connect.ts
  src/routes/authroutes.ts
Labels: Under Review

#13 Ft reset password #184359074
  package-lock.json
  package.json
  src/app.ts
  src/controllers/__tests__/authController.test.ts
  src/controllers/authController.ts
  src/controllers/resetcontrollers.ts
  src/controllers/resetpassword.ts
  src/db/config/config.js
  src/db/migrations/20230207171213-create-users.js
  src/db/models/index.js
  src/db/models/users.js
  src/helper/jwtTokenize.ts
  src/models/token.ts
  src/routes/__tests__/index.test.ts
  src/routes/authroutes.ts
  src/routes/docs.ts
Labels: READY

#23 feat(profile-page): created models to use in profile setup
  package-lock.json
  package.json
  src/app.ts
  src/controllers/authController.ts
  src/controllers/profilepageController.ts
  src/middlewares/verifyToken.ts
  src/models/User.ts
  src/models/profilemodels/Address.ts
  src/models/profilemodels/BillingAdress.ts
  src/models/profilemodels/profile.ts
  src/routes/docs.ts
  src/routes/profileroutes.ts
Labels: WIP

#24 add yarn, config for deployment compatibility
  .gitignore
  package-lock.json
  package.json
  src/app.ts
  src/db/database.ts
Labels: READY
